export type Env=Record<string,boolean>;
export type Expr={type:'var'|'not'|'and'|'or',name?:string,left?:Expr,right?:Expr};
export type Output={name:string;expr:Expr};
export type Row={n:number; v:Env; values:boolean[]};
export type Implicant={bits:string; cells:number[]; term:string; essential?:boolean; parents?:string};

const implicit=(a:string,b:string)=> (/[A-Za-z0-9_')]/.test(a)&&(/[A-Za-z_(!~¬]/.test(b)));
function tokens(source:string){const raw=source.replace(/&&/g,'·').replace(/\|\|/g,'+').replace(/[&*·]/g,'·').replace(/[!~¬]/g,'!').replace(/\s+/g,'');let out:string[]=[];for(let i=0;i<raw.length;){let c=raw[i];if(/[A-Za-z_]/.test(c)){let j=i+1;if(/[A-Z]/.test(c)){while(j<raw.length&&/[a-z0-9_]/.test(raw[j]))j++}else while(j<raw.length&&/[A-Za-z0-9_]/.test(raw[j]))j++;out.push(raw.slice(i,j));i=j}else{out.push(c);i++}}
 const joined:string[]=[];out.forEach((t,i)=>{if(i&&implicit(out[i-1],t))joined.push('·');joined.push(t)});return joined}
export function parseExpr(source:string):Expr{const t=tokens(source);let i=0;const atom=():Expr=>{if(t[i]==='!'){i++;return {type:'not',left:atom()}}if(t[i]==='('){i++;let e=or();if(t[i++]!==')')throw Error('missing closing parenthesis');while(t[i]==="'"){i++;e={type:'not',left:e}}return e}let name=t[i++];if(!name||!/^[A-Za-z_]/.test(name))throw Error(`expected a variable near “${t.slice(Math.max(0,i-1)).join('')}”`);let e:Expr={type:'var',name};while(t[i]==="'"){i++;e={type:'not',left:e}}return e};const and=()=>{let e=atom();while(t[i]==='·'){i++;e={type:'and',left:e,right:atom()}}return e};const or=()=>{let e=and();while(t[i]==='+'){i++;e={type:'or',left:e,right:and()}}return e};let e=or();if(i<t.length)throw Error(`unexpected token “${t[i]}”`);return e}
export function parse(source:string){const used=new Map<string,number>();const outputs:Output[]=source.split(/\n|,/).filter(x=>x.trim()).map((line,index)=>{let m=line.match(/^\s*([A-Za-z_][\w]*)\s*=\s*(.+)\s*$/);if(!m)throw Error(`line ${index+1}: use Name = expression`);let base=m[1],count=(used.get(base)||0)+1;used.set(base,count);return {name:count===1?base:`${base}_${count}`,expr:parseExpr(m[2])}});if(!outputs.length)throw Error('enter at least one output');let names=new Set<string>();const visit=(e:Expr)=>{if(e.type==='var')names.add(e.name!);else if(e.left){visit(e.left);if(e.right)visit(e.right)}};outputs.forEach(x=>visit(x.expr));let vars=[...names];if(vars.length>4)throw Error('Karnaugh maps support up to 4 input variables');return {outputs,vars:vars.sort((a,b)=>a.localeCompare(b))}}
export function evaluate(e:Expr,v:Env):boolean{switch(e.type){case'var':return !!v[e.name!];case'not':return !evaluate(e.left!,v);case'and':return evaluate(e.left!,v)&&evaluate(e.right!,v);case'or':return evaluate(e.left!,v)||evaluate(e.right!,v)}}
export function truthTable(outputs:Output[],vars:string[]):Row[]{return Array.from({length:1<<vars.length},(_,n)=>{let v:Env={};vars.forEach((x,i)=>v[x]=!!(n&(1<<(vars.length-1-i))));return {n,v,values:outputs.map(o=>evaluate(o.expr,v))}})}
const count=(x:string)=>[...x].filter(c=>c==='1').length;const differs=(a:string,b:string)=>{let d=0,p=-1;for(let i=0;i<a.length;i++)if(a[i]!==b[i]){d++;p=i}return d===1?p:-1};
export function simplify(minterms:number[],vars:string[]){if(!minterms.length)return {implicants:[] as Implicant[],stages:[] as Implicant[][]};if(minterms.length===(1<<vars.length))return {implicants:[{bits:'-'.repeat(vars.length),cells:minterms,term:'1',essential:true}],stages:[] as Implicant[][]};let current:Implicant[]=minterms.map(n=>({bits:n.toString(2).padStart(vars.length,'0'),cells:[n],term:'',parents:''}));let primes:Implicant[]=[];let stages:Implicant[][]=[current];while(current.length){let used=new Set<number>(),next:Implicant[]=[];for(let a=0;a<current.length;a++)for(let b=a+1;b<current.length;b++){let p=differs(current[a].bits,current[b].bits);if(p>=0){used.add(a);used.add(b);let bits=current[a].bits.slice(0,p)+'-'+current[a].bits.slice(p+1),cells=[...new Set([...current[a].cells,...current[b].cells])].sort((x,y)=>x-y);if(!next.some(x=>x.bits===bits))next.push({bits,cells,term:'',parents:`${current[a].bits} + ${current[b].bits} (bit ${vars[p]})`})}}current.forEach((x,i)=>{if(!used.has(i))primes.push(x)});if(!next.length)break;current=next;stages.push(current)}
 const term=(bits:string)=>bits.split('').map((b,i)=>b==='-'?'':vars[i]+(b==='0'?"'":'')).join('')||'1';primes=primes.map(x=>({...x,term:term(x.bits)}));let remaining=new Set(minterms),selected:Implicant[]=[];for(const m of minterms){let hits=primes.filter(p=>p.cells.includes(m));if(hits.length===1&&!selected.includes(hits[0])){hits[0].essential=true;selected.push(hits[0]);hits[0].cells.forEach(x=>remaining.delete(x))}}while(remaining.size){let best=primes.filter(p=>!selected.includes(p)).sort((a,b)=>[...remaining].filter(x=>b.cells.includes(x)).length-[...remaining].filter(x=>a.cells.includes(x)).length)[0];if(!best)break;selected.push(best);best.cells.forEach(x=>remaining.delete(x))}return {implicants:selected,stages:stages.map(s=>s.map(x=>({...x,term:term(x.bits)}))),primes}}
export const exprText=(e:Expr):string=>e.type==='var'?e.name!:e.type==='not'?`${exprText(e.left!)}'`: `(${exprText(e.left!)} ${e.type==='and'?'·':'+'} ${exprText(e.right!)})`;
export const sop=(items:Implicant[])=>items.map(x=>x.term).join(' + ')||'0';
